/**
 * GENERATED by `scripts/gen-session-format-catalog.ts` — do not edit by hand.
 * The direct imports make historical readability independent of mounted plugins.
 */

import { KNOWN_SESSION_EVENT_TYPES } from '@deepseek-ai/dsh-session'
import { createSessionFormatCatalog } from '@deepseek-ai/dsh-session-format'
import { validateInstalledCurrentSessionArtifact, validateInstalledCurrentSessionHeader } from './current.ts'
import { assertReleasedV1Header, releasedV0SessionFormatCodec, releasedV1SessionFormatCodec, restoreReleasedV1Artifact, sessionFormatV0ToV1 } from '@deepseek-ai/dsh-session-format-v0-to-v1'

/** Physical codec dispatch and complete adjacent chain, independent of mounted plugins. */
export const sessionFormatCatalog = createSessionFormatCatalog({
  currentVersion: 1,
  codecs: [releasedV0SessionFormatCodec, releasedV1SessionFormatCodec],
  migrations: [sessionFormatV0ToV1],
  restoreCurrent(artifact) {
    const restored = restoreReleasedV1Artifact(artifact, KNOWN_SESSION_EVENT_TYPES)
    validateInstalledCurrentSessionArtifact(restored)
    return restored
  },
  restoreCurrentHeader(header) {
    assertReleasedV1Header(header)
    validateInstalledCurrentSessionHeader(header)
    return header
  },
})
